export const en = 
{
  meta: {
    title: "Avocado.ai | AI-Native Security Operations & Validation",
    description: "SenseL connects visibility, AI-assisted reasoning, human governance, control validation, and auditable evidence into a continuous improvement loop.",
  },
  nav: [
    ["SenseL Platform", "/platform"],
    ["Solutions", "#solutions"],
    ["Field Proof", "#field-proof"],
    ["Founders", "/company/founders"],
    ["Trust Center", "/trust"],
    ["Resources", "/resources"],
  ],
  login: "Customer Login",
  talk: "Book a Strategy Workshop",
  language: "繁中",
  hero: {
    eyebrow: "AI-NATIVE SECURITY OPERATIONS & VALIDATION",
    title: "Turn security events into a traceable, testable, continuously improving defense loop.",
    description: "Avocado.ai SenseL connects EDR, NDR, WAF, OT, IoMT, CTI, and operational context into Evidence Episodes—helping teams understand risk, complete investigations, validate controls, and preserve audit-ready evidence.",
    primary: "Explore SenseL Platform",
    secondary: "View Solutions",
    proofLabel: "Built for high-trust industries",
    proof: ["Healthcare & IoMT", "Semiconductor & OT", "SMB Security Operations", "Secure AI Governance"],
  },
  problems: {
    eyebrow: "THE OPERATING GAP",
    title: "More tools do not automatically create a path to measurable improvement.",
    description: "SenseL is not designed as another alert dashboard. It brings fragmented signals, asset context, human judgment, and validation results into one governed operating flow.",
    items: [
      ["Fragmented signals", "Endpoint, network, WAF, cloud, and OT alerts remain isolated and difficult to reconstruct."],
      ["Missing field context", "Technical severity alone does not express clinical, production, or operational impact."],
      ["Unvalidated response", "Blocking or patching rarely includes control re-test and continuous regression."],
      ["Evidence cannot be reused", "Investigation notes, audit material, and management reporting are repeatedly rebuilt by hand."],
    ],
  },
  loop: {
    eyebrow: "SENSEL CLOSED LOOP",
    title: "From Observe to Improve, every decision keeps its evidence.",
    description: "Ingestion, context, AI reasoning, human approval, control validation, and regression learning operate as one loop.",
    steps: [
      ["01", "Observe", "Ingest and normalize security and operational data"],
      ["02", "Contextualize", "Connect assets, identities, networks, and business context"],
      ["03", "Reason", "Build Episodes, attack narratives, and risk priority"],
      ["04", "Approve", "Keep people accountable for high-impact decisions"],
      ["05", "Validate", "Test controls through scenarios, exercises, and re-test"],
      ["06", "Improve", "Feed results into rules, models, and governance"],
    ],
    highlight: "The value of AI is not another answer. The answer should have sources, responsibility boundaries, a re-test path, and a measurable effect on defense.",
  },
  solutionsTitle: "One platform, three practical market entry points.",
  solutionsDescription: "Start from current tools and field constraints, establish an acceptable operating outcome, then expand into continuous validation and AI governance.",
  solutions: [
    {
      slug: "managed-security",
      kicker: "SMB & MANAGED SECURITY",
      title: "SenseL Managed Security",
      summary: "For organizations without a full SOC, connect endpoint, network, WAF, intelligence, incident analysis, and recurring improvement reporting.",
      audience: ["SMBs and distributed retail environments", "Existing SI and MSSP customers", "Multi-site organizations needing central governance"],
      challenges: ["Alert volume exceeds available staff", "Tools lack a shared risk language", "Service outcomes are difficult to demonstrate"],
      capabilities: ["EDR, NDR, and WAF integration", "AI Episode correlation and grading", "Threat context and investigation guidance", "Service workflow and improvement tracking", "Management reporting and evidence export"],
      outcomes: ["Shorter triage and handoff", "Consistent service outcomes and priorities", "A sustainable operating layer over existing security investments"],
    },
    {
      slug: "fab-intelligence",
      kicker: "SEMICONDUCTOR ENMS & OT",
      title: "SenseL Fab Intelligence",
      summary: "Bring CT, gateways, equipment hierarchy, energy, and OT security context into one governed data and anomaly-validation architecture.",
      audience: ["Fab facilities and energy teams", "OT and IT security teams", "Operations requiring ISO 50001 evidence"],
      challenges: ["Data quality and hierarchy are inconsistent", "Energy anomalies lack production and security context", "PoC findings do not become sustained operations"],
      capabilities: ["CT and gateway ingestion", "Asset hierarchy and baseline management", "Energy and OT anomaly correlation", "AI-assisted cause and avoidable-loss analysis", "Evidence packaging and continuous validation"],
      outcomes: ["More trustworthy and explainable data", "Better energy and resilience decisions", "A governed foundation for cross-fab expansion"],
    },
    {
      slug: "healthcare-resilience",
      kicker: "HEALTHCARE & IOMT",
      title: "SenseL Healthcare Resilience",
      summary: "Combine EDR, network, WAF, IoMT, threat intelligence, and field exercises to improve healthcare visibility, response, and regression validation.",
      audience: ["Hospital IT and security teams", "Medical-device and network operators", "Institutions needing field exercises and compliance evidence"],
      challenges: ["Endpoints and medical devices have different lifecycles", "Operational ownership is distributed and disruption is unacceptable", "High-risk events lack field-specific validation"],
      capabilities: ["Central Windows and Linux EDR management", "Network, WAF, and IoMT correlation", "Asset groups and responsibility boundaries", "High-risk isolation with human approval", "Exercises, re-test, and Evidence Episodes"],
      outcomes: ["Cross-source visibility", "Response improvement without compromising clinical continuity", "Exercise results converted into trackable control improvement"],
    },
  ],
  fieldProof: {
    eyebrow: "ANONYMOUS FIELD PROOF",
    title: "Build trust through verifiable field outcomes first.",
    description: "The public version uses anonymous, qualitative, governed wording. Customer identities, metrics, and relationship status require explicit permission before publication.",
    items: [
      ["Healthcare", "Deployment and validation", "Heterogeneous endpoints and medical environments", "Establish endpoint coverage, Linux compatibility, group responsibility, and high-risk response workflows."],
      ["Semiconductor", "Paid PoC", "Fab data and energy anomaly analysis", "Validate CT and gateway ingestion, data quality, hierarchy context, and explainable improvement opportunities."],
      ["Managed Security", "Solution build-out", "Multi-source security operations", "Turn WAF, EDR, NDR, intelligence, and incident analysis into a repeatable service model."],
    ],
  },
  founders: {
    eyebrow: "FOUNDERS & LEADERSHIP",
    title: "Commercial execution and technical trust belong in the same product decisions.",
    description: "Avocado.ai is led by complementary founders: one focused on market, customer success, and operations; the other on SenseL architecture, AI security, and validation. Titles and public biographies remain subject to formal approval.",
    people: [
      ["Rain Chung", "鍾雨靜", "Co-Founder & CEO (pending final approval)", "Company strategy, go-to-market, customer success, partnerships, and operations."],
      ["Eric Mao, Ph.D.", "毛敬豪 博士", "Co-Founder & CTO / Chief Architect (pending final approval)", "SenseL architecture, XDR, OT and IoMT, CTI, security validation, and secure AI governance."],
    ],
  },
  integrations: ["Wazuh", "Syslog", "SNMPv3", "Suricata", "WAF", "OT Edge", "CTI", "BAS / Purple Team"],
  trust: {
    eyebrow: "TRUST BY DESIGN",
    title: "Put security, privacy, and claims governance into the release process.",
    description: "The public site and future authenticated customer portal use separate applications, identity, APIs, and data boundaries.",
    items: [
      ["Data boundary", "The public site stores no customer telemetry, reports, credentials, or tenant data."],
      ["Human governance", "High-impact decisions, isolation, and public claims retain an accountable approval path."],
      ["Evidence first", "Incidents, validation, and improvement results remain traceable through Episodes."],
      ["Minimum disclosure", "Unapproved customer names, metrics, SLAs, certifications, and partner claims stay private."],
    ],
  },
  resources: {
    eyebrow: "RESOURCES",
    title: "Methods, field proof, and governance for real decisions.",
    items: [
      ["Field Note", "Threat-Informed Healthcare Resilience", "Convert healthcare threat scenarios into endpoint, network, IoMT, and regression validation."],
      ["Architecture", "Evidence Episode & Closed-Loop Validation", "A traceable architecture from signals and reasoning to human approval and control re-test."],
      ["Governance", "Secure AI for Security Operations", "Define model purpose, data sources, approval authority, validation, and continuous oversight."],
    ],
  },
  final: {
    eyebrow: "START WITH A SCOPED WORKSHOP",
    title: "Define the operating problem, responsibility boundary, and acceptance outcome first.",
    description: "We start from current tools, field constraints, data conditions, and risk priorities to design a testable and extensible delivery path.",
    primary: "Book a Strategy Workshop",
    secondary: "Contact Avocado.ai",
  },
  pages: {
    platform: ["SenseL Platform", "Connect visibility, reasoning, approval, validation, and improvement through one control plane.", "SenseL is not another isolated dashboard. Evidence Episodes make data, context, AI reasoning, human accountability, and validation results traceable and reusable."],
    founders: ["Founders & Leadership", "Use complementary leadership to connect market needs, product decisions, and technical evidence.", "The founder page currently uses titles and biographies pending approval. It makes no unverified endorsement, customer, or quantitative claim."],
    trust: ["Trust Center", "Explain the responsibilities and boundaries of the public site, SenseL platform, and future customer portal.", "The Trust Center will progressively cover security architecture, privacy, deployment, vulnerability reporting, supply chain, and service assurance. Sensitive evidence is shared only through controlled processes."],
    resources: ["Resources", "Threat intelligence, field proof, and secure AI governance methods.", "Resources focus on decisions that can be acted on: mapping threats to assets, validating controls, turning data into evidence, and operating AI under explicit governance."],
    contact: ["Book a Workshop", "Define the problem before choosing technology and scope.", "Do not send patient data, production credentials, network diagrams, unpublished vulnerabilities, or incident evidence through public channels. Approved email and booking destinations are enabled through environment configuration."],
  },
  footer: "AI-native Security Operations & Validation Platform",
} as const;
