export const zh = 
{
  meta: {
    title: "Avocado.ai｜AI 原生資安營運與驗證平台",
    description: "SenseL 串聯可視性、AI 關聯分析、人工治理、控制驗證與可稽核證據，讓資安改善成為持續閉環。",
  },
  nav: [
    ["SenseL 平台", "/platform"],
    ["解決方案", "#solutions"],
    ["實證場域", "#field-proof"],
    ["創辦團隊", "/company/founders"],
    ["Trust Center", "/trust"],
    ["資源", "/resources"],
  ],
  login: "客戶登入",
  talk: "預約策略工作坊",
  language: "EN",
  hero: {
    eyebrow: "AI-NATIVE SECURITY OPERATIONS & VALIDATION",
    title: "把資安事件，變成可追溯、可驗證、可持續改善的防禦閉環。",
    description: "Avocado.ai 的 SenseL 將 EDR、NDR、WAF、OT、IoMT、CTI 與營運脈絡整理成 Evidence Episode，協助團隊看懂風險、完成調查、驗證控制並留下稽核證據。",
    primary: "探索 SenseL 平台",
    secondary: "查看解決方案",
    proofLabel: "為高信任產業打造",
    proof: ["醫療與 IoMT", "半導體與 OT", "中小企業資安營運", "AI 資安治理"],
  },
  problems: {
    eyebrow: "THE OPERATING GAP",
    title: "工具很多，防禦仍缺少一條能完成改善的路徑。",
    description: "SenseL 不以增加另一個告警面板為目標，而是把分散訊號、資產脈絡、人工判斷與驗證結果放進同一個可治理流程。",
    items: [
      ["訊號分散", "端點、網路、WAF、雲端與 OT 告警彼此孤立，事件難以還原。"],
      ["缺少場域脈絡", "技術嚴重度無法直接反映醫療、產線或營運影響。"],
      ["回應不可驗證", "完成封鎖或修補後，缺少控制重測與持續回歸。"],
      ["證據無法重用", "調查紀錄、稽核材料與管理報告反覆人工整理。"],
    ],
  },
  loop: {
    eyebrow: "SENSEL CLOSED LOOP",
    title: "從 Observe 到 Improve，讓每一次判斷都能留下證據。",
    description: "資料接入、脈絡化、AI 推理、人工核准、控制驗證與回歸學習形成同一條閉環。",
    steps: [
      ["01", "Observe", "接入並正規化安全與營運資料"],
      ["02", "Contextualize", "串聯資產、身分、網路與業務脈絡"],
      ["03", "Reason", "建立 Episode、攻擊故事與風險排序"],
      ["04", "Approve", "由人員核准高影響判斷與動作"],
      ["05", "Validate", "透過情境、演練與重測驗證控制"],
      ["06", "Improve", "將結果回饋規則、模型與治理流程"],
    ],
    highlight: "AI 的價值不只是產生答案，而是讓答案有來源、有責任邊界、可以重測，並真正改善防禦。",
  },
  solutionsTitle: "一個平台，三條可落地的市場路徑。",
  solutionsDescription: "從既有工具與場域限制出發，先建立可驗收的營運成果，再逐步擴展到持續驗證與 AI 治理。",
  solutions: [
    {
      slug: "managed-security",
      kicker: "SMB & MANAGED SECURITY",
      title: "SenseL Managed Security",
      summary: "為缺乏完整 SOC 人力的組織，整合端點、網路、WAF、情資、事件分析與週期性改善報告。",
      audience: ["中小企業與連鎖場域", "既有 SI／MSSP 客戶", "需要集中治理的多據點組織"],
      challenges: ["告警量超過人力負荷", "工具分散且缺少統一風險語言", "報告與服務成果難以量化"],
      capabilities: ["EDR／NDR／WAF 資料整合", "AI Episode 關聯與分級", "情資脈絡與調查建議", "服務工單與改善追蹤", "管理報告與證據匯出"],
      outcomes: ["縮短事件判讀與交接時間", "建立一致的服務成果與優先序", "讓既有安全投資形成可持續營運流程"],
    },
    {
      slug: "fab-intelligence",
      kicker: "SEMICONDUCTOR ENMS & OT",
      title: "SenseL Fab Intelligence",
      summary: "將 CT、閘道器、設備階層、能源與 OT 安全脈絡放進同一個資料治理與異常驗證架構。",
      audience: ["半導體廠務與能源管理團隊", "OT／IT 資安團隊", "需要 ISO 50001 證據鏈的營運單位"],
      challenges: ["資料品質與設備階層難以一致", "能源異常缺少生產與資安脈絡", "PoC 成果難以轉為持續營運"],
      capabilities: ["CT 與閘道資料接入", "資產階層與基線管理", "能源與 OT 異常關聯", "AI 輔助根因與可避免損失分析", "證據封裝與持續驗證"],
      outcomes: ["提升資料可信度與異常可解釋性", "支援節能與韌性決策", "建立從 PoC 到跨廠擴充的治理基礎"],
    },
    {
      slug: "healthcare-resilience",
      kicker: "HEALTHCARE & IOMT",
      title: "SenseL Healthcare Resilience",
      summary: "結合 EDR、網路、WAF、IoMT、威脅情資與實證演練，建立醫療場域的可視性、應變與回歸驗證。",
      audience: ["醫院資訊與資安團隊", "醫療設備與網路管理單位", "需要場域演練與合規證據的機構"],
      challenges: ["端點與醫療設備生命週期差異大", "維運責任分散且不能任意中斷", "高風險事件缺少場域化驗證"],
      capabilities: ["Windows／Linux EDR 集中管理", "網路、WAF 與 IoMT 事件關聯", "資產群組與責任邊界", "高風險隔離與人工核准", "情境演練、複測與 Evidence Episode"],
      outcomes: ["提升跨來源事件可視性", "在不中斷醫療服務前提下改善回應", "把演練結果轉成可追蹤的控制改善"],
    },
  ],
  fieldProof: {
    eyebrow: "ANONYMOUS FIELD PROOF",
    title: "先以可驗證的場域成果建立信任。",
    description: "公開版本僅使用匿名、定性且經治理的描述；客戶名稱、數字與合作狀態須取得正式許可後才能發布。",
    items: [
      ["Healthcare", "部署與驗證中", "異質端點與醫療設備場域", "建立端點納管、Linux 相容性驗證、群組責任與高風險事件回應流程。"],
      ["Semiconductor", "付費 PoC", "Fab 資料與能源異常分析", "驗證 CT 與閘道資料接入、資料品質、階層脈絡及可解釋的改善機會。"],
      ["Managed Security", "方案建置中", "多來源安全營運整合", "把 WAF、EDR、NDR、情資與事件分析轉成可重複交付的服務模式。"],
    ],
  },
  founders: {
    eyebrow: "FOUNDERS & LEADERSHIP",
    title: "商業落地與技術可信度，同時進入產品決策。",
    description: "Avocado.ai 由互補的創辦團隊推動：一端負責市場、客戶成功與營運，一端負責 SenseL 架構、AI 資安與驗證方法。職稱與公開履歷仍依正式核准流程管理。",
    people: [
      ["Rain Chung", "鍾雨靜", "Co-Founder & CEO（待最終核准）", "公司策略、Go-to-Market、客戶成功、合作夥伴與營運。"],
      ["Eric Mao, Ph.D.", "毛敬豪 博士", "Co-Founder & CTO / Chief Architect（待最終核准）", "SenseL 產品架構、XDR、OT／IoMT、CTI、安全驗證與 Secure AI Governance。"],
    ],
  },
  integrations: ["Wazuh", "Syslog", "SNMPv3", "Suricata", "WAF", "OT Edge", "CTI", "BAS / Purple Team"],
  trust: {
    eyebrow: "TRUST BY DESIGN",
    title: "把安全、隱私與主張治理放進發布流程。",
    description: "公開官網與未來的登入式客戶 Portal 採不同應用、身分、API 與資料邊界。",
    items: [
      ["資料邊界", "公開網站不承載客戶 telemetry、報告、憑證或租戶資料。"],
      ["人工治理", "高影響判斷、隔離與公開主張保留責任人與核准軌跡。"],
      ["證據導向", "事件、驗證與改善結果以可追溯 Episode 保存。"],
      ["最小揭露", "未核准的客戶名稱、數字、SLA、認證與夥伴關係不公開。"],
    ],
  },
  resources: {
    eyebrow: "RESOURCES",
    title: "以方法、實證與治理支持真正的決策。",
    items: [
      ["Field Note", "Threat-Informed Healthcare Resilience", "如何把醫療威脅情境轉成端點、網路、IoMT 與回歸驗證。"],
      ["Architecture", "Evidence Episode & Closed-Loop Validation", "從訊號、推理、人工核准到控制重測的可稽核架構。"],
      ["Governance", "Secure AI for Security Operations", "界定模型用途、資料來源、核准權限、驗證與持續監督。"],
    ],
  },
  final: {
    eyebrow: "START WITH A SCOPED WORKSHOP",
    title: "先定義營運問題、責任邊界與可驗收成果。",
    description: "我們將從既有工具、場域限制、資料條件與風險優先序出發，規劃一條可驗證、可擴充的導入路徑。",
    primary: "預約策略工作坊",
    secondary: "聯絡 Avocado.ai",
  },
  pages: {
    platform: ["SenseL Platform", "把可視性、推理、核准、驗證與改善連成同一個控制平面。", "SenseL 不是另一個孤立的 Dashboard；它以 Evidence Episode 為核心，讓資料、脈絡、AI 推理、人工責任與驗證結果可以被追溯與重用。"],
    founders: ["Founders & Leadership", "用互補領導，連結市場需求、產品決策與技術證據。", "創辦團隊頁目前使用待核准的職稱與簡介，不引用未經確認的外部背書、客戶名稱或量化成果。"],
    trust: ["Trust Center", "清楚說明公開網站、SenseL 平台與未來客戶 Portal 的責任邊界。", "Trust Center 將逐步提供安全架構、隱私、部署模式、弱點通報、供應鏈與服務保證資訊；敏感證據僅透過受控流程分享。"],
    resources: ["Resources", "Threat intelligence、場域實證與 AI 資安治理方法。", "資源內容將聚焦可操作的決策：威脅如何映射資產、控制如何驗證、資料如何成為證據，以及 AI 如何在清楚治理下運作。"],
    contact: ["Book a Workshop", "先定義問題，再選擇技術與導入範圍。", "公開聯絡頁不收集病患資料、生產憑證、網路圖、未公開弱點或事件證據。正式信箱與預約連結將透過環境設定啟用。"],
  },
  footer: "AI-native Security Operations & Validation Platform",
} as const;
